import express from 'express';
import cors from 'cors';
import multer from 'multer';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from "@google/genai";
import { Buffer } from "buffer";

// Load environment variables
dotenv.config({ path: '.env.local' });
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Serve static files from the build directory
app.use(express.static(path.join(__dirname, 'dist')));

// Serve public files (like widget.js)
app.use(express.static(path.join(__dirname, 'public')));

// File Upload Config
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 5 * 1024 * 1024 } // 5MB limit
});

// --- API Logic (Inlined from externalApiService.ts) ---

const getApiClient = () => {
    const apiKey = process.env.MODEL_API_KEY;
    if (!apiKey) {
        console.warn("WARNING: MODEL_API_KEY is not set. Using placeholder.");
        return new GoogleGenAI({ apiKey: "YOUR_API_KEY_HERE" });
    }
    return new GoogleGenAI({ apiKey });
};

const bufferToBase64 = (buffer) => {
    return buffer.toString('base64');
};

const generateVirtualTryOn = async (userImageBuffer, userMimeType, productImageUrl) => {
    try {
        const ai = getApiClient();

        // Fetch product image
        const productResp = await fetch(productImageUrl);
        if (!productResp.ok) throw new Error("Failed to fetch product image from URL");
        const productArrayBuffer = await productResp.arrayBuffer();
        const productBase64 = Buffer.from(productArrayBuffer).toString('base64');
        const productMimeType = productResp.headers.get('content-type') || 'image/jpeg';

        const model = 'gemini-2.5-flash-image';
        const prompt = `
      You are an expert fashion assistant. 
      I will provide two images:
      1. A photo of a person.
      2. A photo of a product (clothing, accessory, or footwear).
      
      Your task: Generate a realistic image of the person from the first image wearing or using the product from the second image. 
      Maintain the person's pose, lighting, and facial features. Adapt the product to fit naturally.
      Return ONLY the image.
    `;

        const response = await ai.models.generateContent({
            model: model,
            contents: {
                parts: [
                    { text: prompt },
                    {
                        inlineData: {
                            mimeType: userMimeType,
                            data: bufferToBase64(userImageBuffer)
                        }
                    },
                    {
                        inlineData: {
                            mimeType: productMimeType,
                            data: productBase64
                        }
                    }
                ]
            }
        });

        const parts = response.candidates?.[0]?.content?.parts;
        if (parts) {
            for (const part of parts) {
                if (part.inlineData && part.inlineData.data) {
                    return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
                }
            }
        }
        throw new Error("No image generated by the external API.");

    } catch (error) {
        const apiKey = process.env.MODEL_API_KEY || '';
        let errStr = String(error);
        if (apiKey && apiKey.length > 0) {
            errStr = errStr.replace(new RegExp(apiKey, 'g'), 'YOUR_API_KEY_HERE');
        }
        console.error("External API Error:", errStr);
        throw new Error("External processing failed.");
    }
};

// --- Routes ---

app.post('/api/generate', upload.single('user_image'), async (req, res) => {
    try {
        const userImage = req.file;
        const productImageUrl = req.body.product_image_url;

        if (!userImage) return res.status(400).json({ success: false, error: 'User image is required' });
        if (!productImageUrl) return res.status(400).json({ success: false, error: 'Product image URL is required' });

        const generatedImageBase64 = await generateVirtualTryOn(
            userImage.buffer,
            userImage.mimetype,
            productImageUrl
        );

        res.json({ success: true, image: generatedImageBase64 });

    } catch (error) {
        console.error("Server Error:", error.message);
        res.status(500).json({ success: false, error: 'Processing failed. Please try again.' });
    }
});

// Catch-all handler for any request that doesn't match the above
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
    const apiKey = process.env.MODEL_API_KEY;
    if (!apiKey) {
        console.warn("WARNING: MODEL_API_KEY is not set.");
    } else {
        const maskedKey = apiKey.length > 4
            ? apiKey.substring(0, 4) + "*".repeat(apiKey.length - 4)
            : "****";
        console.log(`API Key loaded: ${maskedKey}`);
    }
});
